import json
import os

from fastapi import APIRouter, HTTPException, Query
from services.gutenberg import search_books, get_book_meta, get_book_text
from services.db import get_cached_book, save_book, list_cached_books
from services.splitter import build_chapters

# Popular books manifest generated by scripts/seed_books.py
_POPULAR_BOOKS_PATH = os.path.join(os.path.dirname(__file__), "..", "popular_books.json")
_popular_cache: list[dict] | None = None


router = APIRouter(prefix="/books", tags=["books"])


@router.get("/search")
async def search(
    q: str = Query(..., description="Search query"),
    language: str = Query("", description="Language code e.g. en, de, fr"),
    page: int = Query(1, ge=1),
):
    return await search_books(q, language, page)


@router.get("/cached")
async def cached_books():
    """List books already stored in the local database."""
    return await list_cached_books()


@router.get("/popular")
async def popular_books(language: str = ""):
    """Return the curated list of popular Gutenberg books.

    The list is generated offline by scripts/seed_books.py and stored as
    a JSON manifest. It covers the top ~100 books across English, German,
    and French.
    """
    global _popular_cache
    if _popular_cache is None:
        if not os.path.isfile(_POPULAR_BOOKS_PATH):
            return []
        with open(_POPULAR_BOOKS_PATH, encoding="utf-8") as f:
            _popular_cache = json.load(f)

    if language:
        return [b for b in _popular_cache if language in b.get("languages", [])]
    return _popular_cache


@router.get("/{book_id}")
async def book_meta(book_id: int):
    cached = await get_cached_book(book_id)
    if cached:
        return {k: v for k, v in cached.items() if k not in ("text", "cached_at", "images")}
    try:
        return await get_book_meta(book_id)
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.get("/{book_id}/chapters")
async def book_chapters(book_id: int):
    """
    Return book split into chapters.
    Serves from local DB if cached, otherwise fetches from Gutenberg and caches.
    """
    cached = await get_cached_book(book_id)

    if cached and cached.get("text"):
        text = cached["text"]
        meta = {k: v for k, v in cached.items() if k not in ("text", "cached_at", "images")}
    else:
        try:
            meta, text = await _fetch_and_cache(book_id)
        except Exception as e:
            msg = str(e) or type(e).__name__
            raise HTTPException(status_code=404, detail=msg)

    chapters = build_chapters(text)
    return {
        "book_id": book_id,
        "meta": meta,
        "chapters": [{"title": c.title, "text": c.text} for c in chapters],
    }


async def _fetch_and_cache(book_id: int) -> tuple[dict, str]:
    meta = await get_book_meta(book_id)
    text = await get_book_text(book_id)
    await save_book(book_id, meta, text)
    return meta, text
