import asyncio
import json
import logging
import os
from typing import AsyncIterator

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from services.gutenberg import search_books, get_book_meta, get_book_text, get_book_html
from services.db import (
    get_cached_book,
    save_book,
    list_cached_books,
)
from services.splitter import build_chapters, build_chapters_from_html
from services.auth import get_current_user, get_optional_user, decrypt_api_key

logger = logging.getLogger(__name__)

# Popular books manifest generated by scripts/seed_books.py
_POPULAR_BOOKS_PATH = os.path.join(os.path.dirname(__file__), "..", "popular_books.json")
_popular_cache: list[dict] | None = None


router = APIRouter(prefix="/books", tags=["books"])


@router.get("/search")
async def search(
    q: str = Query(..., description="Search query"),
    language: str = Query("", description="Language code e.g. en, de, fr"),
    page: int = Query(1, ge=1),
):
    return await search_books(q, language, page)


@router.get("/cached")
async def cached_books():
    """List books already stored in the local database."""
    return await list_cached_books()


@router.get("/popular")
async def popular_books(
    language: str = "",
    page: int = Query(1, ge=1),
    per_page: int = Query(50, ge=1, le=200),
):
    """Return a paginated slice of the curated popular Gutenberg books manifest.

    The manifest is either the new dict format {language: [books]} produced by
    seed_books.py --collections, or the legacy flat list.
    """
    global _popular_cache
    if _popular_cache is None:
        if not os.path.isfile(_POPULAR_BOOKS_PATH):
            return {"books": [], "total": 0, "page": page, "per_page": per_page}
        with open(_POPULAR_BOOKS_PATH, encoding="utf-8") as f:
            raw = json.load(f)
        # Normalize: ensure list fields are always arrays, never null.
        def _norm(book: dict) -> dict:
            for field in ("authors", "languages", "subjects"):
                if not isinstance(book.get(field), list):
                    book[field] = []
            return book
        if isinstance(raw, dict):
            _popular_cache = {k: [_norm(b) for b in v] for k, v in raw.items()}
        else:
            _popular_cache = [_norm(b) for b in raw]

    if isinstance(_popular_cache, dict):
        books = _popular_cache.get(language, _popular_cache.get("", []))
    else:
        books = (
            [b for b in _popular_cache if language in b.get("languages", [])]
            if language
            else _popular_cache
        )

    total = len(books)
    start = (page - 1) * per_page
    return {
        "books": books[start : start + per_page],
        "total": total,
        "page": page,
        "per_page": per_page,
    }


@router.get("/{book_id}/translation-status")
async def translation_status(book_id: int, target_language: str):
    """Return book-level translation progress for the reader banner.

    Includes:
      - total_chapters (as split by the splitter)
      - translated_chapters (cached in translations table)
      - queue_pending / queue_running / queue_failed (per-book per-lang
        counts from the translation_queue table) — lets the reader show
        "3/21 chapters still processing" during a background run.
      - bulk_active: legacy one-shot bulk job, kept for back-compat.
    """
    import aiosqlite
    from services.db import count_translations_for_book, DB_PATH
    from services.bulk_translate import manager as bulk_manager

    cached = await get_cached_book(book_id)
    if not cached:
        raise HTTPException(status_code=404, detail="Book not found")
    total_chapters = 0
    if cached.get("text"):
        # Use the shared resolver so total_chapters matches what the reader
        # displays (and what the queue worker processes).
        from services.book_chapters import split_with_html_preference
        chapters = await split_with_html_preference(book_id, cached["text"])
        total_chapters = len(chapters)

    cached_translations = await count_translations_for_book(book_id, target_language)

    # Pull queue stats for this (book, language) in one grouped query.
    queue_counts: dict[str, int] = {}
    async with aiosqlite.connect(DB_PATH) as db:
        async with db.execute(
            """SELECT status, COUNT(*) FROM translation_queue
               WHERE book_id=? AND target_language=?
               GROUP BY status""",
            (book_id, target_language),
        ) as cursor:
            async for row in cursor:
                queue_counts[row[0]] = row[1]

    # Is a bulk job currently touching this book?
    bulk_active = False
    bulk_state = await bulk_manager().status()
    if bulk_state and bulk_state.status == "running":
        bulk_active = (
            bulk_state.current_book_id == book_id
            and bulk_state.target_language == target_language
        )

    return {
        "book_id": book_id,
        "target_language": target_language,
        "total_chapters": total_chapters,
        "translated_chapters": cached_translations,
        "queue_pending": queue_counts.get("pending", 0),
        "queue_running": queue_counts.get("running", 0),
        "queue_failed": queue_counts.get("failed", 0),
        "queue_done": queue_counts.get("done", 0),
        "bulk_active": bulk_active,
    }


@router.get("/{book_id}/chapters/{chapter_index}/queue-status")
async def chapter_queue_status(
    book_id: int,
    chapter_index: int,
    target_language: str,
    _user: dict = Depends(get_current_user),
):
    """Per-chapter queue lookup for the reader page.

    Any logged-in user can call this — the reader needs it before firing an
    on-demand translate to avoid duplicating work the background worker is
    already scheduled to do.
    """
    if not await get_cached_book(book_id):
        raise HTTPException(status_code=404, detail="Book not found")
    from services.translation_queue import queue_status_for_chapter
    return await queue_status_for_chapter(book_id, chapter_index, target_language)


@router.get("/{book_id}/chapters/{chapter_index}/translation")
async def get_chapter_translation(
    book_id: int,
    chapter_index: int,
    target_language: str,
    _user: dict = Depends(get_current_user),
):
    """Return the cached translation if available, 404 otherwise. Never enqueues."""
    target_language = target_language.lower().split("-")[0]
    from services.db import get_cached_translation_with_meta
    cached = await get_cached_translation_with_meta(book_id, chapter_index, target_language)
    if not cached:
        raise HTTPException(status_code=404, detail="Translation not cached")
    return {
        "status": "ready",
        "paragraphs": cached["paragraphs"],
        "provider": cached.get("provider"),
        "model": cached.get("model"),
        "title_translation": cached.get("title_translation"),
    }


class RequestTranslationBody(BaseModel):
    target_language: str


@router.post("/{book_id}/chapters/{chapter_index}/translation")
async def request_chapter_translation(
    book_id: int,
    chapter_index: int,
    req: RequestTranslationBody,
    user: dict | None = Depends(get_optional_user),
):
    """Unified reader-side translation endpoint.

    Reader page calls this when the user enables Translate for a chapter.
    Three outcomes, returned in a single response shape:

    - status="ready" → the translation is already cached, paragraphs returned
      (served to anyone — no auth required for cache hits)
    - status="pending" / "running" → already in the queue, reader polls
    - If not yet queued, this call enqueues it with a high priority
      (user actively waiting) and returns status="pending" with position.
      Login is required to enqueue new translations.
    """
    from services.db import get_cached_translation_with_meta
    from services.translation_queue import (
        enqueue, queue_status_for_chapter, worker,
    )

    target_language = req.target_language.lower().split("-")[0]

    # 0. Already cached? Served to anyone — no auth required for cache hits.
    # Book existence is not checked for cache hits (book may have been removed
    # after translation was stored).
    cached = await get_cached_translation_with_meta(
        book_id, chapter_index, target_language,
    )
    if cached:
        return {
            "status": "ready",
            "paragraphs": cached["paragraphs"],
            "provider": cached.get("provider"),
            "model": cached.get("model"),
            "title_translation": cached.get("title_translation"),
        }

    # 0a. Book must exist before we can enqueue a new translation.
    book_meta = await get_cached_book(book_id)
    if not book_meta:
        raise HTTPException(status_code=404, detail="Book not found")

    # 0b. Guard: reject same-language translation.
    source = (book_meta.get("languages") or [None])[0]
    if source and source.lower().split("-")[0] == target_language:
        raise HTTPException(
            status_code=400,
            detail="Cannot translate to the same language as the original.",
        )

    # 1. New translation requires login.
    if user is None:
        raise HTTPException(
            status_code=401,
            detail="Login required to translate this chapter.",
        )

    # 3. Already queued / running?
    qstatus = await queue_status_for_chapter(
        book_id, chapter_index, target_language,
    )
    if qstatus["queued"]:
        return {
            "status": qstatus["status"],  # 'pending' or 'running'
            "position": qstatus["position"],
            "attempts": qstatus["attempts"],
        }

    # 4. Require user's own Gemini key — do not drain the admin queue key.
    raw_key = user.get("gemini_key")
    try:
        decrypted_key = decrypt_api_key(raw_key) if raw_key else None
    except HTTPException:
        decrypted_key = None
    if not decrypted_key:
        raise HTTPException(
            status_code=403,
            detail="A Gemini API key is required to translate chapters. Please add one in your profile settings.",
        )

    # 5. Not yet queued — enqueue with high priority. Reader-initiated
    # enqueues jump ahead of admin auto-enqueue (priority=100) and
    # admin per-book enqueue (priority=50) because a user is watching.
    queued_by = user.get("email") or user.get("name") or f"user#{user.get('id')}"
    await enqueue(
        book_id, chapter_index, target_language,
        priority=10,
        queued_by=queued_by,
    )
    worker().wake()
    fresh = await queue_status_for_chapter(
        book_id, chapter_index, target_language,
    )
    return {
        "status": fresh["status"],
        "position": fresh["position"],
        "attempts": 0,
    }


@router.post("/{book_id}/translations/enqueue-all")
async def enqueue_all_chapters(
    book_id: int,
    req: RequestTranslationBody,
    user: dict = Depends(get_current_user),
):
    """Queue every not-yet-translated chapter of a book for one language.

    Reader-side counterpart to the admin panel's per-book + Translate
    button. Accepts any authenticated user; queued items use
    priority=20 — above auto-enqueue (100) and admin per-book (50) so
    the user who clicked is served ahead of background rescans, but
    below the active reader's priority=10 so the chapter they're
    currently staring at still wins.
    """
    target_language = req.target_language.lower().split("-")[0]
    book_meta = await get_cached_book(book_id)
    if not book_meta:
        raise HTTPException(status_code=404, detail="Book not found")
    source = (book_meta.get("languages") or [None])[0]
    if source and source.lower().split("-")[0] == target_language:
        raise HTTPException(
            status_code=400,
            detail="Cannot translate to the same language as the original.",
        )

    from services.translation_queue import enqueue_for_book, worker

    queued_by = user.get("email") or user.get("name") or f"user#{user.get('id')}"
    enqueued = await enqueue_for_book(
        book_id,
        target_languages=[target_language],
        priority=20,
        queued_by=queued_by,
    )
    worker().wake()
    return {"ok": True, "enqueued": enqueued}


@router.post("/{book_id}/chapters/{chapter_index}/translation/retry")
async def retry_chapter_translation(
    book_id: int,
    chapter_index: int,
    req: RequestTranslationBody,
    user: dict = Depends(get_current_user),
):
    """Re-queue a single chapter whose queue row is in 'failed' state.

    Distinct from `request_chapter_translation` because that endpoint uses
    INSERT OR IGNORE — a failed row would stay failed forever. Retry is an
    explicit action: admin or reader clicks a button. Resets the queue row
    to pending + attempts=0 and bumps priority to 10 (reader-initiated).
    """
    if not await get_cached_book(book_id):
        raise HTTPException(status_code=404, detail="Book not found")

    from services.translation_queue import enqueue, queue_status_for_chapter, worker

    target_language = req.target_language.lower().split("-")[0]
    queued_by = user.get("email") or user.get("name") or f"user#{user.get('id')}"
    await enqueue(
        book_id, chapter_index, target_language,
        priority=10,
        reset_failed=True,
        queued_by=queued_by,
    )
    worker().wake()
    fresh = await queue_status_for_chapter(
        book_id, chapter_index, target_language,
    )
    return {
        "status": fresh["status"],
        "position": fresh["position"],
        "attempts": 0,
    }


@router.get("/{book_id}")
async def book_meta(book_id: int):
    cached = await get_cached_book(book_id)
    if cached:
        return {k: v for k, v in cached.items() if k not in ("text", "cached_at", "images")}
    try:
        return await get_book_meta(book_id)
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.get("/{book_id}/chapters")
async def book_chapters(book_id: int):
    """
    Return book split into chapters.
    Serves from local DB if cached, otherwise fetches from Gutenberg and caches.

    Splitting strategy:
      1. Try Gutenberg's HTML edition (<div class="chapter"> is semantically
         clean — much better for hierarchical books like War and Peace).
      2. Fall back to regex-based splitting on the plain text otherwise.
    """
    cached = await get_cached_book(book_id)

    if cached and cached.get("text"):
        text = cached["text"]
        meta = {k: v for k, v in cached.items() if k not in ("text", "cached_at", "images")}
    else:
        try:
            meta, text = await _fetch_and_cache(book_id)
        except Exception as e:
            msg = str(e) or type(e).__name__
            raise HTTPException(status_code=404, detail=msg)

    from services.book_chapters import split_with_html_preference
    chapters = await split_with_html_preference(book_id, text)
    return {
        "book_id": book_id,
        "meta": meta,
        "chapters": [{"title": c.title, "text": c.text} for c in chapters],
    }


async def _fetch_and_cache(book_id: int) -> tuple[dict, str]:
    meta = await get_book_meta(book_id)
    text = await get_book_text(book_id)
    await save_book(book_id, meta, text)
    return meta, text


# ══════════════════════════════════════════════════════════════════════════════
# Interactive book import — streams progress via Server-Sent Events
# ══════════════════════════════════════════════════════════════════════════════

def _sse(event: str, data: dict) -> str:
    """Format a single SSE message."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


@router.get("/{book_id}/import-stream")
async def import_stream(
    book_id: int,
    user: dict | None = Depends(get_optional_user),
):
    """Stream import progress for a book via Server-Sent Events.

    Stages:
      fetching   — downloading book text from Gutenberg (if not cached)
      splitting  — computing chapter structure
      done       — all steps complete

    Translation is NOT started here. After import the client shows a cost-
    confirmation panel; the user explicitly enqueues via POST
    /books/{id}/translations/enqueue-all.

    Idempotent: skips already-cached work.
    All books are publicly accessible without login.
    """

    async def generator() -> AsyncIterator[str]:
        try:
            # ── 1. Fetch book text ─────────────────────────────────────────
            yield _sse("stage", {"stage": "fetching", "message": "Fetching book…"})
            cached = await get_cached_book(book_id)
            if cached and cached.get("text"):
                meta = {k: v for k, v in cached.items()
                        if k not in ("text", "cached_at", "images")}
                text = cached["text"]
                yield _sse("stage", {"stage": "fetching", "message": "Already cached",
                                     "progress": 100})
            else:
                try:
                    meta, text = await _fetch_and_cache(book_id)
                except Exception as e:
                    yield _sse("error", {"stage": "fetching", "message": str(e)})
                    return

            source_language = (meta.get("languages") or ["en"])[0]
            yield _sse("meta", {
                "book_id": book_id,
                "title": meta.get("title", ""),
                "source_language": source_language,
            })

            # ── 2. Split chapters ───────────────────────────────────────────
            yield _sse("stage", {"stage": "splitting", "message": "Splitting chapters…"})
            chapters = build_chapters(text)
            total_words = sum(len(c.text.split()) for c in chapters)
            yield _sse("chapters", {
                "total": len(chapters),
                "total_words": total_words,
                "titles": [c.title or f"Chapter {i + 1}" for i, c in enumerate(chapters)],
            })

            yield _sse("done", {"book_id": book_id})

        except asyncio.CancelledError:
            # Client disconnected — FastAPI will raise this
            raise
        except Exception as e:
            logger.exception("Import stream crashed")
            yield _sse("error", {"stage": "unknown", "message": str(e)})

    return StreamingResponse(
        generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",  # disable buffering on any reverse proxy
        },
    )
